#!/bin/bash

set -e 

apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

echo "# Ubuntu Trusty" > /etc/apt/sources.list.d/docker.list
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >> /etc/apt/sources.list.d/docker.list

apt-get update

apt-get purge -y lxc-docker* docker-engine

apt-get install -y docker-engine

echo "DOCKER_OPTS=\"-l warn\"" >> /etc/default/docker

service docker restart

usermod -a -G docker guoxi

ps aux | grep docker
